<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/captured-state-guards';$workspace=$package.'/var/compatibility-captured-state-guards-'.bin2hex(random_bytes(8));mkdir($workspace);$sources=require $fixture.'/sources.php';foreach($sources as $path=>$bytes){file_put_contents($workspace.'/'.$path,$bytes);}
require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';$worker=compatibilityProductionWorker($package,$workspace,$fixture,'CAPTURED_WARNING_PREP_ONLY','CapturedWarningDraftPlugin','CapturedStateGuardPlugin');
require $package.'/vendor/autoload.php';
$finder=new PhpParser\NodeFinder;$nodes=Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource::parse($sources['cases.php']);$proofs=Ichinya\Laramago\Analyzer\CapturedStateGuardSource::compile($nodes);$cases=[];
foreach($finder->find($nodes,static fn($n):bool=>$n instanceof PhpParser\Node\Stmt\ClassMethod||$n instanceof PhpParser\Node\Stmt\Function_) as $scope){$name=$scope->name->name;$sites=[];foreach($proofs as $proof){if($proof['scope']['name']===$name || str_ends_with($proof['scope']['name'],'\\'.$name)){$sites[implode(':',$proof['selectedSite']['span'])]=$proof['selectedSite']['span'];}}$cases[$name]=['positive'=>in_array($name,['threshold','equality','nestedInitialization','writtenValue','visited'],true),'sites'=>$sites];}
file_put_contents($workspace.'/source-case-manifest.json',json_encode($cases,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php'],'includes'=>['contracts.php']]];$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$canonical=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};
$key=static function(array $issue):string{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return $a['span']['start']['offset'].':'.$a['span']['end']['offset'].':'.$issue['code'].':'.$issue['message'];}}return '';};
$rows=static fn(string $stage):array=>array_map(static fn(string $l):array=>json_decode($l,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$stage.'-observer.jsonl',FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES));
$native=$run('native','observe');$admitted=[];$sites=[];foreach($rows('native') as $row){if($row['stage']==='captured-state-warning'&&$row['alwaysKeep']&&$row['proof']['remove']){$site=implode(':',$row['span']);$sites[$site]=true;$admitted[$site.':'.$row['wholeNativeEnvelope']['code'].':'.$row['wholeNativeEnvelope']['message']]=true;}}
foreach($cases as $name=>$case){$hits=array_intersect_key($sites,$case['sites']);if($case['positive']&&$hits===[]){throw new RuntimeException('No genuine native admitted positive: '.$name.'; retained '.$workspace);}if(!$case['positive']&&$hits!==[]){throw new RuntimeException('Near miss admitted: '.$name.'; retained '.$workspace);}}
$expected=array_values(array_filter($native,static fn(array $i):bool=>!isset($admitted[$key($i)])));$draft=$run('draft','draft');if($canonical($expected)!==$canonical($draft)){throw new RuntimeException('Any non-target full DTO changed; retained '.$workspace);}if(count(array_filter($native,static fn(array $i):bool=>$i['level']==='Error'))===0){throw new RuntimeException('No independent genuine Error to preserve.');}
if($canonical($run('preserve','preserve'))!==$canonical($native)||$canonical($run('draft-three-workers','draft',3))!==$canonical($draft)){throw new RuntimeException('Preserve/worker-count drift; retained '.$workspace);}
foreach(['cache-field-type'=>4,'cache-visited-function'=>1] as $mode=>$minimum){if($canonical($run($mode,$mode))!==$canonical($native)){throw new RuntimeException('Native cache refusal drift; retained '.$workspace);}$controls=array_filter($rows($mode),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)<$minimum){throw new RuntimeException('Missing genuine cache control for every selected role; retained '.$workspace);}}
$original=file_get_contents($workspace.'/contracts.php');$changed=str_replace('public ?\\Closure $reader','public static ?\\Closure $reader',$original);if($changed===$original){throw new RuntimeException('Static field source control was a no-op.');}file_put_contents($workspace.'/contracts.php',$changed);$changedNative=$run('source-field-native','observe');$changedDraft=$run('source-field-draft','draft');
$changedExpected=$changedNative;foreach($rows('source-field-native') as $r){if($r['stage']==='captured-state-warning'&&$r['proof']['remove']){if($r['proof']['source']['storage']!==null){throw new RuntimeException('Static physical field accepted.');}$target=implode(':',$r['span']).':'.$r['wholeNativeEnvelope']['code'].':'.$r['wholeNativeEnvelope']['message'];$changedExpected=array_values(array_filter($changedExpected,static fn(array $i):bool=>$key($i)!==$target));}}
if($canonical($changedExpected)!==$canonical($changedDraft)){throw new RuntimeException('Changed-source residual DTO drift.');}file_put_contents($workspace.'/contracts.php',$original);if($canonical($run('source-restored','draft'))!==$canonical($draft)){throw new RuntimeException('Restoration drift.');}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','originalIds'=>['W027','W092','W093','W094','W095'],'nativeCount'=>count($native),'draftCount'=>count($draft),'removedWarningDTOs'=>count($admitted),'wholeResidualDTOsPreserved'=>true,'nativeTypesChanged'=>false],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));echo "PASS: captured-state Warning policy; retained $workspace\n";
