<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/captured-this-local-bindings';$workspace=$package.'/var/compatibility-captured-this-local-bindings-'.bin2hex(random_bytes(8));mkdir($workspace);
foreach(require $fixture.'/sources.php' as $path=>$bytes){if(!is_dir(dirname($workspace.'/'.$path))){mkdir(dirname($workspace.'/'.$path),recursive:true);}file_put_contents($workspace.'/'.$path,$bytes);}
require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';$worker=compatibilityProductionWorker($package,$workspace,$fixture,'LOCAL_CAPTURE_PREP_ONLY','LocalCaptureDraftPlugin','GuardedMethodCompatibilityPlugin');
$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php'],'includes'=>['contracts.php']]];
$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$canonical=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};
$select=static function(array $issues,int $line):array{return array_values(array_filter($issues,static function(array $issue)use($line):bool{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return basename($a['span']['file_id']['name'])==='cases.php'&&$a['span']['start']['line']+1===$line&&$issue['code']==='non-existent-method';}}return false;}));};
$native=$run('native','observe');$draft=$run('draft','draft');$remaining=$native;$positives=[4,5,6,7,8,10,11,12];
foreach($positives as $line){$before=$select($native,$line);if(count($before)!==1 || $before[0]['level']!=='Error' || $select($draft,$line)!==[]){throw new RuntimeException('Missing genuine local capture positive at '.$line.'; retained '.$workspace);}$remaining=array_values(array_filter($remaining,static fn(array $i):bool=>$i!==$before[0]));}
if($canonical($remaining)!==$canonical($draft)){throw new RuntimeException('Any non-target complete native DTO changed; retained '.$workspace);}
if($canonical($run('draft-three-workers','draft',3))!==$canonical($draft)){throw new RuntimeException('One/three worker drift; retained '.$workspace);}
if($canonical($run('preserve','preserve'))!==$canonical($native)){throw new RuntimeException('AlwaysKeep/preserve changed native DTOs; retained '.$workspace);}
foreach(['cache-local-return'=>6,'cache-callback-reference'=>8] as $mode=>$required){$control=$run($mode,$mode);if($canonical($control)!==$canonical($native)){throw new RuntimeException('Metadata refusal changed native DTOs; retained '.$workspace);}$rows=array_map(static fn(string $line):array=>json_decode($line,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$mode.'-observer.jsonl',FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES));$rows=array_filter($rows,static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['restored']);$names=array_unique(array_map(static fn(array $r):string=>$r['caller']['class'].'::'.$r['caller']['method'],$rows));if(count($names)<$required){throw new RuntimeException('No genuine mutation for every positive; retained '.$workspace);}}
$path=$workspace.'/contracts.php';$original=file_get_contents($path);$changed=str_replace('$this->callbacks[]=$callback;','$callback->bindTo($this);',$original);if($changed===$original){throw new RuntimeException('Source control was a no-op.');}file_put_contents($path,$changed);
$changedNative=$run('source-storage-changed-native','observe');$changedDraft=$run('source-storage-changed-draft','draft');if($canonical($changedNative)!==$canonical($changedDraft)){throw new RuntimeException('Changed callback transport remained trusted; retained '.$workspace);}file_put_contents($path,$original);if($canonical($run('source-restored','draft'))!==$canonical($draft)){throw new RuntimeException('Source restoration changed complete result; retained '.$workspace);}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','originalId'=>'E052','nativeCount'=>count($native),'draftCount'=>count($draft),'positives'=>$positives,'wholeResidualDTOsPreserved'=>true,'currentRegistryPreserved'=>true,'sourceOnlyApplication'=>true],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));echo "PASS: local captured-this guard; retained $workspace\n";
