<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/collection-offset-guards';$workspace=$package.'/var/compatibility-collection-offset-guards-'.bin2hex(random_bytes(8));mkdir($workspace);$manifest=json_decode(file_get_contents($fixture.'/primary/manifest.json'),true,flags:JSON_THROW_ON_ERROR);
foreach($manifest['files'] as $path=>$entry){$bytes=file_get_contents($fixture.'/primary/'.$path);if(hash('sha256',$bytes)!==$entry['sourceSha256']){throw new RuntimeException('Prepared public primary declaration drift.');}if(!is_dir(dirname($workspace.'/'.$path))){mkdir(dirname($workspace.'/'.$path),recursive:true);}file_put_contents($workspace.'/'.$path,$bytes);}
$cases=require $fixture.'/fixture-cases.php';file_put_contents($workspace.'/cases.php',$cases);file_put_contents($workspace.'/composer.json','{}');require $package.'/vendor/autoload.php';require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';
$pureCases=static function(string $path):array{return require $path;};$mixinCases=$pureCases($fixture.'/model-mixin-cases.php');$semanticCases=$pureCases($fixture.'/native-profile-cases.php');if($mixinCases!==['cases'=>11,'positiveCount'=>3]||$semanticCases!==['semanticNegativeCases'=>138]){throw new RuntimeException('The isolated portable source matrices changed.');}
$sourceCaseCount=0;foreach(require $fixture.'/source-cases.php' as $name=>$contents){$sourceProofs=Ichinya\Laramago\Analyzer\CollectionOffsetGuardSource::compile(Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource::parse($contents));$kinds=array_count_values(array_column($sourceProofs,'kind'));$expectedKinds=match($name){'local','unrelated-first-class-callable'=>['nullable-collection-offset'=>1,'defensive-indexed-model'=>1],'captured'=>['nullable-collection-offset'=>1],default=>[]};ksort($kinds);ksort($expectedKinds);if($kinds!==$expectedKinds){throw new RuntimeException('Wrong closed source regression '.$name);}$sourceCaseCount++;}
$proofs=Ichinya\Laramago\Analyzer\CollectionOffsetGuardSource::compile(Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource::parse($cases));$positives=[];foreach($proofs as $site=>$p){$positives[$site]=$p['kind'];}if(count($positives)!==3){throw new RuntimeException('Three source-positive routes required.');}
file_put_contents($workspace.'/source-case-manifest.json',json_encode(['sourceCases'=>$sourceCaseCount,'sourcePositiveSites'=>$positives,'fixtureRuntimeExecuted'=>false,'nativeProfilesUseCertifiedProductionDefaults'=>true],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
$worker=compatibilityProductionWorker($package,$workspace,$fixture,'COLLECTION_BOUNDARY_FIXTURE','CollectionOffsetGuardDraftPlugin','CollectionOffsetGuardPlugin');$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php'],'includes'=>array_keys($manifest['files'])]];
$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$normalize=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};
$rows=static fn(string $stage):array=>array_map(static fn(string $s):array=>json_decode($s,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$stage.'-observer.jsonl',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES));
$key=static function(array $issue):string{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return $a['span']['start']['offset'].':'.$a['span']['end']['offset'].':'.$issue['code'].':'.$issue['message'];}}return '';};
$probe=$run('native-profile-probe','observe');$profiles=[];$seen=[];
foreach($rows('native-profile-probe') as $row){if($row['stage']!=='collection-boundary'||!$row['proof']['remove']){continue;}$site=implode(':',$row['span']);if(!isset($positives[$site])){throw new RuntimeException('Unsupported source site produced admission metadata.');}$seen[$site]=true;foreach($row['proof']['observedLibraryNativeProfiles'] as $symbol=>$profile){if($symbol!=='Illuminate\\Support\\Collection::keyBy'&&isset($profiles[$symbol])&&$profiles[$symbol]!==$profile['sha256']){throw new RuntimeException('Native selected library metadata drift.');}$profiles[$symbol]=$profile['sha256'];}}
if(count($seen)!==3||count($profiles)!==4){throw new RuntimeException('No three genuine complete Collection positives; retained '.$workspace);}file_put_contents($workspace.'/observed-library-native-hashes.json',json_encode($profiles,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
if(in_array('--observe-only',$argv,true)){echo "OBSERVED ONLY: $workspace\n";exit(0);}
$native=$run('native','observe');if($normalize($native)!==$normalize($probe)){throw new RuntimeException('AlwaysKeep or selected metadata changed whole DTOs.');}$admitted=[];
foreach($rows('native') as $row){if($row['stage']==='collection-boundary'&&$row['alwaysKeep']&&$row['proof']['remove']){$site=implode(':',$row['span']);if(!isset($positives[$site])){throw new RuntimeException('Unsupported source near miss admitted.');}$envelope=$row['wholeNativeEnvelope'];$admitted[$site.':'.$envelope['code'].':'.$envelope['message']]=true;}}
if(count($admitted)!==3){throw new RuntimeException('Three genuine Warning admissions required.');}$expected=array_values(array_filter($native,static fn(array $i):bool=>!isset($admitted[$key($i)])));$draft=$run('draft','draft');if($normalize($expected)!==$normalize($draft)){throw new RuntimeException('Complete residual DTO parity failed.');}
if(array_filter($native,static fn(array $i):bool=>$i['level']==='Error')===[]){throw new RuntimeException('Missing independent real Error.');}
if($normalize($run('preserve','preserve'))!==$normalize($native)||$normalize($run('draft-three-workers','draft',3))!==$normalize($draft)||$normalize($run('native-three-workers','observe',3))!==$normalize($native)){throw new RuntimeException('Preserve or host-count parity failed.');}
foreach(['cache-query-return','cache-key-by-return','cache-storage-object','cache-caller-reference','cache-key-by-constraint','cache-key-by-doc-origin','cache-model-mixin'] as $mode){if($normalize($run($mode,$mode))!==$normalize($native)){throw new RuntimeException('SDK mutation changed any whole DTO.');}$controls=array_filter($rows($mode),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)!==3){throw new RuntimeException('Every selected positive needs a changed native cache refusal/restoration.');}}
if($normalize($run('cache-key-by-population','cache-key-by-population'))!==$normalize($native)){throw new RuntimeException('Population-only native mutation changed whole DTOs.');}
$controls=array_filter($rows('cache-key-by-population'),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['populationOnlyAccepted']&&!$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)!==3){throw new RuntimeException('Every genuine positive needs a meaningful accepted population-only mutation/restoration.');}
$original=file_get_contents($workspace.'/cases.php');$changed=str_replace("keyBy('id')","keyBy('label')",$original,$changes);if($changes!==2){throw new RuntimeException('Source key mutation is not meaningful.');}file_put_contents($workspace.'/cases.php',$changed);
if($normalize($run('source-other-key-native','observe'))!==$normalize($run('source-other-key-draft','draft'))){throw new RuntimeException('Unsupported literal key was not preserved.');}file_put_contents($workspace.'/cases.php',$original);if($normalize($run('source-restored','draft'))!==$normalize($draft)){throw new RuntimeException('Source restoration changed accepted output.');}
$unknownMixin=str_replace('@mixin \\Illuminate\\Database\\Eloquent\\Model','@mixin \\stdClass',$original,$mixinChanges);if($mixinChanges!==1){throw new RuntimeException('One source Model-parent mixin mutation required.');}file_put_contents($workspace.'/cases.php',$unknownMixin);
if($normalize($run('source-unknown-mixin-native','observe'))!==$normalize($run('source-unknown-mixin-draft','draft'))){throw new RuntimeException('Unknown source/native mixin was incorrectly admitted.');}file_put_contents($workspace.'/cases.php',$original);if($normalize($run('source-mixin-restored','draft'))!==$normalize($draft)){throw new RuntimeException('Source Model-parent mixin restoration drift.');}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','sourceCases'=>$sourceCaseCount,'nativeCount'=>count($native),'draftCount'=>count($draft),'removedWarnings'=>count($admitted),'wholeResidualDTOsPreserved'=>true,'nativeTypesChanged'=>false,'undefinedKeysPreserved'=>true],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));echo "PASS: Collection defensive boundary; retained $workspace\n";
