<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/defensive-response-guards';$workspace=$package.'/var/compatibility-defensive-response-guards-'.bin2hex(random_bytes(8));mkdir($workspace);$sources=require $fixture.'/sources.php';$sources['vendor/ichinya/laratesto/src/Testing/LaravelResponse.php']=file_get_contents($package.'/tests/fixtures/analysis/http-contracts.php.stub');
foreach($sources as $path=>$bytes){if(!is_dir(dirname($workspace.'/'.$path))){mkdir(dirname($workspace.'/'.$path),recursive:true);}file_put_contents($workspace.'/'.$path,$bytes);}
require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';$worker=compatibilityProductionWorker($package,$workspace,$fixture,'RESPONSE_GUARD_PREP_ONLY','ResponseGuardDraftPlugin','DefensiveResponseGuardPlugin');
require $package.'/vendor/autoload.php';$sourceProofs=Ichinya\Laramago\Analyzer\DefensiveResponseGuardSource::compile(Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource::parse($sources['cases.php']));$positiveSites=[];foreach($sourceProofs as $p){if($p['scope']['name']==='props'){$positiveSites[implode(':',$p['selectedSite']['span'])]=true;}}
file_put_contents($workspace.'/source-case-manifest.json',json_encode(['originalIds'=>['W020','W139','W141'],'positiveSites'=>$positiveSites,'negativeMethods'=>['ordinary','rebound','nullable','documented','otherField']],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php'],'includes'=>['vendor']]];$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$normalize=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};$rows=static fn(string $stage):array=>array_map(static fn(string $l):array=>json_decode($l,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$stage.'-observer.jsonl',FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES));
$key=static function(array $issue):string{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return $a['span']['start']['offset'].':'.$a['span']['end']['offset'].':'.$issue['code'].':'.$issue['message'];}}return '';};
$native=$run('native','observe');$admitted=[];$hits=[];foreach($rows('native') as $r){if($r['stage']==='response-defensive-guard'&&$r['alwaysKeep']&&$r['proof']['remove']){$site=implode(':',$r['span']);if(!isset($positiveSites[$site])){throw new RuntimeException('Near miss was admitted; retained '.$workspace);}$hits[$site]=true;$admitted[$site.':'.$r['wholeNativeEnvelope']['code'].':'.$r['wholeNativeEnvelope']['message']]=true;}}
if(count($hits)!==3){throw new RuntimeException('Missing three individually genuine page/props Warning sites; retained '.$workspace);}$expected=array_values(array_filter($native,static fn(array $i):bool=>!isset($admitted[$key($i)])));$draft=$run('draft','draft');if($normalize($expected)!==$normalize($draft)){throw new RuntimeException('Any non-target whole DTO changed; retained '.$workspace);}if(array_filter($native,static fn(array $i):bool=>$i['level']==='Error')===[]){throw new RuntimeException('Missing independent genuine Error.');}
if($normalize($run('preserve','preserve'))!==$normalize($native)||$normalize($run('draft-three-workers','draft',3))!==$normalize($draft)){throw new RuntimeException('Preserve/worker-count drift.');}
foreach(['cache-forwarder-return','cache-page-property'] as $mode){if($normalize($run($mode,$mode))!==$normalize($native)){throw new RuntimeException('Native cache refusal changed DTOs.');}$controls=array_filter($rows($mode),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)<count($admitted)){throw new RuntimeException('Every selected Warning requires real native cache mutation.');}}
$library=$workspace.'/vendor/ichinya/laratesto/src/Testing/LaravelResponse.php';$original=file_get_contents($library);$changed=str_replace("return \$this->frameworkAssertion('inertiaPage', [\$key]);",'return [];',$original);if($changed===$original){throw new RuntimeException('Physical forwarder source control was a no-op.');}file_put_contents($library,$changed);
if($normalize($run('source-forwarder-native','observe'))!==$normalize($run('source-forwarder-draft','draft'))){throw new RuntimeException('Changed physical page source remained trusted.');}file_put_contents($library,$original);if($normalize($run('source-restored','draft'))!==$normalize($draft)){throw new RuntimeException('Source restoration drift.');}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','originalIds'=>['W020','W139','W141'],'nativeCount'=>count($native),'draftCount'=>count($draft),'removedWarnings'=>count($admitted),'nativeTypesChanged'=>false,'wholeResidualDTOsPreserved'=>true],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));echo "PASS: response defensive Warning policy; retained $workspace\n";
