<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/selected-chunk-model-warning';$workspace=$package.'/var/compatibility-selected-chunk-model-warning-'.bin2hex(random_bytes(8));mkdir($workspace);
$manifest=json_decode(file_get_contents($fixture.'/primary/manifest.json'),true,flags:JSON_THROW_ON_ERROR);$sourceReceipt=['inventedCases'=>15,'readOnlyHelperSourceMutationSites'=>14];
foreach($manifest['files'] as $path=>$entry){$bytes=file_get_contents($fixture.'/primary/'.$path);if(hash('sha256',$bytes)!==$entry['sourceSha256']){throw new RuntimeException('Prepared primary declaration drift.');}if(!is_dir(dirname($workspace.'/'.$path))){mkdir(dirname($workspace.'/'.$path),recursive:true);}file_put_contents($workspace.'/'.$path,$bytes);}
require $package.'/vendor/autoload.php';$sourceDirectory=$workspace.'/source-cases';mkdir($sourceDirectory);$sourceCount=0;
foreach(require $fixture.'/source-cases.php' as $name=>$case){$path=$sourceDirectory.'/'.$name.'.php';file_put_contents($path,$case['source']);$source=new Ichinya\Laramago\Analyzer\GuardedStringCastContracts($sourceDirectory);$file=$source->read($path);$calls=(new PhpParser\NodeFinder)->find($file['nodes'],static fn(PhpParser\Node $n):bool=>$n instanceof PhpParser\Node\Expr\MethodCall&&$n->name instanceof PhpParser\Node\Identifier&&strtolower($n->name->name)==='adjust');$proof=count($calls)===1?(new Ichinya\Laramago\Analyzer\SelectedChunkModelWarningSource($sourceDirectory))->lexical($source,$file,$calls[0]):null;if(($proof!==null)!==$case['positive']){throw new RuntimeException('Wrong closed source case '.$name);}$sourceCount++;unset($file,$calls,$source,$proof);}
if($sourceCount!==16){throw new RuntimeException('Complete source case matrix required.');}
$cases=require $fixture.'/fixture-cases.php';file_put_contents($workspace.'/cases.php',$cases);file_put_contents($workspace.'/composer.json','{}');require $package.'/vendor/autoload.php';require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';
$worker=compatibilityProductionWorker($package,$workspace,$fixture,'SELECTED_CHUNK_MODEL_WARNING_FIXTURE','SelectedChunkModelWarningDraftPlugin','SelectedChunkModelWarningPlugin');$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php'],'includes'=>array_keys($manifest['files'])]];$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$normalize=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};$rows=static fn(string $stage):array=>array_map(static fn(string $line):array=>json_decode($line,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$stage.'-observer.jsonl',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES));$key=static function(array $issue):string{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return $a['span']['start']['offset'].':'.$a['span']['end']['offset'].':'.$issue['code'].':'.$issue['message'];}}return '';};
$probe=$run('native-profile-probe','observe');$profiles=[];$admitted=[];foreach($rows('native-profile-probe') as $row){if(!$row['proof']['remove']||$row['proof']['stage']!=='current-declared-method-on-selected-chunk-model'){continue;}$admitted[]=$row;foreach($row['proof']['observedNativeProfiles'] as $symbol=>$profile){if(isset($profiles[$symbol])&&$profiles[$symbol]!==$profile['sha256']){throw new RuntimeException('Selected genuine native profile drift.');}$profiles[$symbol]=$profile['sha256'];}}
if(count($admitted)!==1||count($profiles)!==4){throw new RuntimeException('One complete genuine model method positive required; retained '.$workspace);}file_put_contents($workspace.'/observed-native-hashes.json',json_encode($profiles,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));if(in_array('--observe-only',$argv,true)){echo "OBSERVED ONLY: $workspace\n";exit(0);}
$native=$run('native','observe');if($normalize($native)!==$normalize($probe)){throw new RuntimeException('AlwaysKeep profile probe changed whole native DTOs.');}$target=array_values(array_filter($rows('native'),static fn(array $r):bool=>$r['proof']['remove']));if(count($target)!==1){throw new RuntimeException('Exactly one current genuine model Warning must be admitted.');}$span=implode(':',$target[0]['span']);$i=$target[0]['wholeNativeEnvelope'];$removed=$span.':'.$i['code'].':'.$i['message'];$expected=array_values(array_filter($native,static fn(array $i):bool=>$key($i)!==$removed));$draft=$run('draft','draft');if($normalize($draft)!==$normalize($expected)||array_filter($draft,static fn(array $i):bool=>$i['level']==='Error')===[]){throw new RuntimeException('Whole residual DTO or independent Error preservation failed.');}
if($normalize($run('preserve','preserve'))!==$normalize($native)||$normalize($run('native-three-workers','observe',3))!==$normalize($native)||$normalize($run('draft-three-workers','draft',3))!==$normalize($draft)){throw new RuntimeException('Preserve/default-engine host-count parity failed.');}
foreach(['cache-helper-formal','cache-helper-reference','cache-callee-static','cache-chunk-return'] as $mode){if($normalize($run($mode,$mode))!==$normalize($native)){throw new RuntimeException('Changed SDK control altered unrelated whole DTOs.');}$controls=array_filter($rows($mode),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)!==1){throw new RuntimeException('A selected genuine native mutation/refusal/restoration is required.');}}
$mutated=str_replace('$ids=[];foreach($batch as $item)','$ids=[];unknown($batch);foreach($batch as $item)',$cases,$changes);if($changes<1||$changes!==$sourceReceipt['readOnlyHelperSourceMutationSites']){throw new RuntimeException('Read-only helper source mutation was vacuous or changed unexpected sites.');}file_put_contents($workspace.'/cases.php',$mutated);if($normalize($run('source-escape-native','observe'))!==$normalize($run('source-escape-draft','draft'))){throw new RuntimeException('Unknown helper collection escape was incorrectly admitted.');}file_put_contents($workspace.'/cases.php',$cases);if($normalize($run('source-restored','draft'))!==$normalize($draft)){throw new RuntimeException('Selected chunk source restoration drift.');}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','inventedCases'=>$sourceReceipt['inventedCases'],'nativeCount'=>count($native),'draftCount'=>count($draft),'selectedWarningsRemoved'=>1,'wholeResidualDTOsPreserved'=>true,'nativeTypesChanged'=>false,'callbackExecuted'=>false,'callerWholeAstRetained'=>false],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));echo "PASS: selected chunk model method; retained $workspace\n";
