<?php
declare(strict_types=1);
$package=dirname(__DIR__);$fixture=__DIR__.'/fixtures/xml-cardinality-guards';$workspace=$package.'/var/compatibility-xml-cardinality-guards-'.bin2hex(random_bytes(8));mkdir($workspace);$sources=require $fixture.'/sources.php';foreach($sources as $path=>$bytes){if(!is_dir(dirname($workspace.'/'.$path))){mkdir(dirname($workspace.'/'.$path),recursive:true);}file_put_contents($workspace.'/'.$path,$bytes);}
require $package.'/tests/fixtures/compatibility-bounded-worker-support.php';$worker=compatibilityProductionWorker($package,$workspace,$fixture,'XML_CARDINALITY_PREP_ONLY','XmlCardinalityDraftPlugin','XmlCardinalityGuardPlugin');
require $package.'/vendor/autoload.php';$proofs=Ichinya\Laramago\Analyzer\XmlCardinalitySource::compile(Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource::parse($sources['cases.php']));$positives=[];foreach($proofs as $p){if($p['scope']['name']!=='checked'){throw new RuntimeException('A source near miss entered the XML grammar.');}$positives[implode(':',$p['selectedSite']['span'])]=true;}if(count($positives)!==1){throw new RuntimeException('Missing invented source positive.');}
file_put_contents($workspace.'/source-case-manifest.json',json_encode(['positiveSites'=>$positives,'fixedBuiltinProfiles'=>true,'fixtureRuntimeExecuted'=>false],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
$config=['php-version'=>'8.5','source'=>['paths'=>['cases.php']]];$run=static fn(string $stage,string $mode,int $workers=1):array=>compatibilityNativeGate($package,$workspace,$worker,$config,$stage,$mode,$workers);
$normalize=static function(array $issues):array{$rows=array_map(static fn(array $i):string=>json_encode($i,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),$issues);sort($rows);return $rows;};$rows=static fn(string $stage):array=>array_map(static fn(string $l):array=>json_decode($l,true,flags:JSON_THROW_ON_ERROR),file($workspace.'/'.$stage.'-observer.jsonl',FILE_SKIP_EMPTY_LINES|FILE_IGNORE_NEW_LINES));
$key=static function(array $issue):string{foreach($issue['annotations'] as $a){if($a['kind']==='Primary'){return $a['span']['start']['offset'].':'.$a['span']['end']['offset'].':'.$issue['code'].':'.$issue['message'];}}return '';};
$sourceCases=require $fixture.'/source-cases.php';$native=$run('native-profile-probe','observe');$profiles=[];$seen=[];foreach($rows('native-profile-probe') as $row){if($row['stage']==='xml-cardinality'&&$row['proof']['remove']){$site=implode(':',$row['span']);if(!isset($positives[$site])){throw new RuntimeException('A near miss produced XML admission metadata.');}$seen[$site]=true;foreach($row['proof']['observedBuiltinProfiles'] as $symbol=>$profile){if(isset($profiles[$symbol])&&$profiles[$symbol]!==$profile['sha256']){throw new RuntimeException('Builtin metadata drift within genuine positive.');}$profiles[$symbol]=$profile['sha256'];}}}
if(count($seen)!==1||count($profiles)!==3){throw new RuntimeException('No genuine complete XML source/native metadata positive; retained '.$workspace);}$references=json_decode(file_get_contents($fixture.'/builtin-profile-hashes.json'),true,flags:JSON_THROW_ON_ERROR);ksort($profiles);ksort($references);if($profiles!==$references){throw new RuntimeException('Genuine current builtin profiles differ from the fixed public reference.');}

$admitted=[];foreach($rowsAfter=$run('native','observe') as $unused){}if($normalize($rowsAfter)!==$normalize($native)){throw new RuntimeException('AlwaysKeep changed whole DTOs.');}foreach($rows('native') as $row){if($row['stage']==='xml-cardinality'&&$row['alwaysKeep']&&$row['proof']['remove']){$site=implode(':',$row['span']);if(!isset($positives[$site])){throw new RuntimeException('A near miss was admitted.');}$admitted[$site.':'.$row['wholeNativeEnvelope']['code'].':'.$row['wholeNativeEnvelope']['message']]=true;}}
if(count($admitted)!==1){throw new RuntimeException('No genuine admitted XML Warning.');}$expected=array_values(array_filter($native,static fn(array $i):bool=>!isset($admitted[$key($i)])));$draft=$run('draft','draft');if($normalize($expected)!==$normalize($draft)){throw new RuntimeException('Any non-target whole DTO changed.');}if(array_filter($native,static fn(array $i):bool=>$i['level']==='Error')===[]){throw new RuntimeException('Missing independent genuine Error.');}
if($normalize($run('preserve','preserve'))!==$normalize($native)||$normalize($run('native-three-workers','observe',3))!==$normalize($native)||$normalize($run('draft-three-workers','draft',3))!==$normalize($draft)){throw new RuntimeException('Preserve or worker-count drift.');}
foreach(['cache-xpath-return','cache-loader-flags','cache-class-flags'] as $mode){if($normalize($run($mode,$mode))!==$normalize($native)){throw new RuntimeException('Native cache refusal changed whole DTOs.');}$controls=array_filter($rows($mode),static fn(array $r):bool=>$r['stage']==='real-native-cache-control'&&$r['genuinePositiveBefore']&&$r['slotsChanged']>0&&$r['deferredAfter']&&$r['completeProofRestored']);if(count($controls)!==1){throw new RuntimeException('Missing genuine changed native cache control.');}}
$file=$workspace.'/cases.php';$original=file_get_contents($file);$changed=str_replace('count($file->metrics)!==1','count($file->metrics)!==3',$original);if($changed===$original){throw new RuntimeException('Cardinality source mutation was a no-op.');}file_put_contents($file,$changed);if($normalize($run('source-count-native','observe'))!==$normalize($run('source-count-draft','draft'))){throw new RuntimeException('Unsupported cardinality remained admitted.');}file_put_contents($file,$original);if($normalize($run('source-restored','draft'))!==$normalize($draft)){throw new RuntimeException('Source restoration drift.');}
file_put_contents($workspace.'/gate-result.json',json_encode(['status'=>'passed','nativeCount'=>count($native),'draftCount'=>count($draft),'removedWarnings'=>count($admitted),'nativeTypesChanged'=>false,'wholeResidualDTOsPreserved'=>true],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));echo "PASS: XML defensive Warning policy; retained $workspace\n";
