<?php
declare(strict_types=1);
namespace Ichinya\Laramago\Analyzer;
use Ichinya\Laramago\Analyzer\DefensiveBoundaryGuardSource as Source;
use PhpParser\{Node,NodeFinder};

/** Literal keyBy reads on a fresh model query; no nullable key or model type is rewritten. */
final class CollectionOffsetGuardSource
{
    public static function compile(array $nodes):array
    {
        $finder=new NodeFinder;$parents=[];$walk=static function(mixed $value,?Node $parent=null)use(&$walk,&$parents):void{if(is_array($value)){foreach($value as $item){$walk($item,$parent);}}elseif($value instanceof Node){if($parent!==null){$parents[spl_object_id($value)]=$parent;}foreach($value->getSubNodeNames() as $name){$walk($value->$name,$value);}}};$walk($nodes);
        $ancestors=static function(Node $node)use($parents):array{$r=[];while(isset($parents[spl_object_id($node)])){$node=$parents[spl_object_id($node)];$r[]=$node;}return $r;};$proofs=[];
        foreach($finder->findInstanceOf($nodes,Node\Expr\ArrayDimFetch::class) as $read){
            if(!$read->var instanceof Node\Expr\Variable||!is_string($read->var->name)||$read->dim===null){continue;}$receiver=$read->var->name;$owner=null;$class=null;$closures=[];
            foreach($ancestors($read) as $ancestor){if($ancestor instanceof Node\Expr\Closure||$ancestor instanceof Node\Expr\ArrowFunction){$closures[]=$ancestor;}if($owner===null&&($ancestor instanceof Node\Stmt\ClassMethod||$ancestor instanceof Node\Stmt\Function_)){$owner=$ancestor;}if($ancestor instanceof Node\Stmt\Class_){$class=$ancestor;break;}}
            if($owner===null||$owner->returnsByRef()||($owner instanceof Node\Stmt\ClassMethod&&($class===null||!isset($class->namespacedName)))){continue;}
            if($finder->findFirst([$owner],static fn(Node $n):bool=>$n instanceof Node\Expr\AssignRef||$n instanceof Node\Stmt\Global_||$n instanceof Node\Stmt\Static_||$n instanceof Node\Expr\ClosureUse&&$n->byRef||$n instanceof Node\Stmt\Foreach_&&$n->byRef)!==null){continue;}
            $capture=true;foreach($closures as $closure){if($closure instanceof Node\Expr\ArrowFunction){$capture=false;break;}$uses=array_values(array_filter($closure->uses,static fn(Node\Expr\ClosureUse $use):bool=>$use->var->name===$receiver&&!$use->byRef));if(count($uses)!==1){$capture=false;break;}}if(!$capture){continue;}
            $assignments=$finder->findInstanceOf([$owner],Node\Expr\Assign::class);$definitions=array_values(array_filter($assignments,static fn(Node\Expr\Assign $a):bool=>$a->var instanceof Node\Expr\Variable&&$a->var->name===$receiver));
            if(count($definitions)!==1){continue;}$definition=$definitions[0];if($definition->getEndFilePos()>=$read->getStartFilePos()||!self::dominates($definition,$read,$ancestors)){continue;}
            $keyBy=$definition->expr;if(!$keyBy instanceof Node\Expr\MethodCall||!self::plain($keyBy)||!self::method($keyBy,'keyBy')||count($keyBy->args)!==1||!$keyBy->args[0]->value instanceof Node\Scalar\String_||$keyBy->args[0]->value->value!=='id'){continue;}
            $producer=$keyBy->var;$intermediate=null;if($producer instanceof Node\Expr\Variable&&is_string($producer->name)){$sourceName=$producer->name;$sources=array_values(array_filter($assignments,static fn(Node\Expr\Assign $a):bool=>$a->var instanceof Node\Expr\Variable&&$a->var->name===$sourceName));if(count($sources)!==1||$sources[0]->getEndFilePos()>=$definition->getStartFilePos()||!self::dominates($sources[0],$definition,$ancestors)){continue;}$intermediate=$sources[0];$producer=$intermediate->expr;}
            $query=self::query($producer);if($query===null){continue;}
            $unsafe=false;foreach($finder->findInstanceOf([$owner],Node\Expr\Variable::class) as $variable){if($variable->name!==$receiver||$variable===$definition->var||$variable->getStartFilePos()<$definition->getStartFilePos()){continue;}$parent=$parents[spl_object_id($variable)]??null;
                if($parent instanceof Node\Expr\ClosureUse||$parent instanceof Node\Expr\ArrayDimFetch&&$parent->var===$variable){continue;}
                if($parent instanceof Node\Expr\MethodCall&&$parent->var===$variable&&self::plain($parent)&&$parent->name instanceof Node\Identifier&&in_array(strtolower($parent->name->name),['keys','isempty','count'],true)){continue;}$unsafe=true;break;}
            foreach($ancestors($read) as $parent){if($parent instanceof Node\Expr\Assign&&self::contains($parent->var,$read)||$parent instanceof Node\Expr\AssignOp&&self::contains($parent->var,$read)||$parent instanceof Node\Expr\AssignRef||$parent instanceof Node\Expr\PreInc||$parent instanceof Node\Expr\PostInc||$parent instanceof Node\Expr\PreDec||$parent instanceof Node\Expr\PostDec||$parent instanceof Node\Stmt\Unset_){$unsafe=true;break;}if($parent instanceof Node\Stmt||$parent instanceof Node\Arg){break;}}
            if($unsafe){continue;}$scope=self::scope($owner,$class);$base=['scope'=>$scope,'receiver'=>$receiver,'definition'=>Source::span($definition),'keyBy'=>Source::span($keyBy),'intermediate'=>$intermediate===null?null:Source::span($intermediate),'query'=>$query,'read'=>Source::span($read),'index'=>Source::span($read->dim),'closures'=>array_map(static fn(Node $n):array=>Source::span($n),$closures),'nativeTypesChanged'=>false];
            $proofs[Source::key(Source::span($read->dim))]=$base+['kind'=>'nullable-collection-offset'];
            $parent=$parents[spl_object_id($read)]??null;$statement=$parent instanceof Node\Expr\Assign?$parents[spl_object_id($parent)]??null:null;
            if($parent instanceof Node\Expr\Assign&&$parent->var instanceof Node\Expr\Variable&&is_string($parent->var->name)&&$statement instanceof Node\Stmt\Expression){
                $container=$parents[spl_object_id($statement)]??null;$statements=$container?->stmts??[];$position=array_search($statement,$statements,true);$guard=$position===false?null:($statements[$position+1]??null);
                if($guard instanceof Node\Stmt\If_&&$guard->else===null&&$guard->elseifs===[]&&$guard->cond instanceof Node\Expr\BooleanNot&&$guard->cond->expr instanceof Node\Expr\Instanceof_&&$guard->cond->expr->expr instanceof Node\Expr\Variable&&$guard->cond->expr->expr->name===$parent->var->name&&$guard->cond->expr->class instanceof Node\Name&&strcasecmp($guard->cond->expr->class->toString(),$query['model'])===0&&count($guard->stmts)===1){
                    $throw=$guard->stmts[0] instanceof Node\Stmt\Expression?$guard->stmts[0]->expr:null;if($throw instanceof Node\Expr\Throw_&&$throw->expr instanceof Node\Expr\New_&&$throw->expr->class instanceof Node\Name&&in_array($throw->expr->class->toString(),['LogicException','RuntimeException'],true)&&count($throw->expr->args)===1&&$throw->expr->args[0] instanceof Node\Arg&&$throw->expr->args[0]->value instanceof Node\Scalar\String_&&!$throw->expr->args[0]->byRef&&!$throw->expr->args[0]->unpack&&$throw->expr->args[0]->name===null){$proofs[Source::key(Source::span($guard->cond))]=$base+['kind'=>'defensive-indexed-model','guard'=>Source::span($guard),'exception'=>$throw->expr->class->toString()];}
                }
            }
        }return $proofs;
    }
    private static function query(?Node $node):?array
    {
        if(!$node instanceof Node\Expr\MethodCall||!self::plain($node)||!self::method($node,'get')||count($node->args)>1){return null;}if($node->args!==[]){$columns=$node->args[0]->value;if(!$columns instanceof Node\Expr\Array_||count($columns->items)>12){return null;}foreach($columns->items as $item){if($item===null||$item->key!==null||$item->byRef||$item->unpack||!$item->value instanceof Node\Scalar\String_){return null;}}}
        $get=Source::span($node);$calls=[];$node=$node->var;while($node instanceof Node\Expr\MethodCall){if(!self::plain($node)||!$node->name instanceof Node\Identifier||!in_array(strtolower($node->name->name),['where','wheredate','wherein','wheremonth','whereyear','orderby','orderbydesc','lockforupdate'],true)){return null;}$calls[]=['name'=>strtolower($node->name->name),'span'=>Source::span($node)];$node=$node->var;}
        if(!$node instanceof Node\Expr\StaticCall||!self::plain($node)||!$node->class instanceof Node\Name||!$node->name instanceof Node\Identifier||strtolower($node->name->name)!=='query'||$node->args!==[]){return null;}return ['model'=>$node->class->toString(),'root'=>Source::span($node),'get'=>$get,'calls'=>$calls];
    }
    private static function plain(Node\Expr\CallLike $call):bool{return !$call->isFirstClassCallable()&&!array_filter($call->args,static fn($a):bool=>!$a instanceof Node\Arg||$a->name!==null||$a->byRef||$a->unpack);}
    private static function method(Node\Expr\MethodCall $call,string $name):bool{return $call->name instanceof Node\Identifier&&strcasecmp($call->name->name,$name)===0;}
    private static function contains(Node $parent,Node $child):bool{return $parent->getStartFilePos()<=$child->getStartFilePos()&&$parent->getEndFilePos()>=$child->getEndFilePos();}
    private static function dominates(Node $definition,Node $read,callable $ancestors):bool{$select=static fn(Node $n):bool=>$n instanceof Node\Stmt\If_||$n instanceof Node\Stmt\Else_||$n instanceof Node\Stmt\ElseIf_||$n instanceof Node\Stmt\Foreach_||$n instanceof Node\Stmt\While_||$n instanceof Node\Stmt\Do_||$n instanceof Node\Stmt\For_||$n instanceof Node\Stmt\TryCatch||$n instanceof Node\Stmt\Catch_||$n instanceof Node\Stmt\Case_;$a=array_reverse(array_filter($ancestors($definition),$select));$b=array_reverse(array_filter($ancestors($read),$select));return array_slice($b,0,count($a))===$a;}
    private static function scope(Node\Stmt\ClassMethod|Node\Stmt\Function_ $scope,?Node\Stmt\Class_ $class):array{$starts=[$scope->getStartFilePos()];foreach($scope->getComments() as $comment){$starts[]=$comment->getStartFilePos();}foreach($scope->attrGroups as $group){$starts[]=$group->getStartFilePos();}return ['class'=>$class?->namespacedName?->toString(),'name'=>$scope instanceof Node\Stmt\Function_?$scope->namespacedName->toString():$scope->name->name,'span'=>Source::span($scope),'startAlternatives'=>$starts,'static'=>$scope instanceof Node\Stmt\ClassMethod&&$scope->isStatic(),'parameters'=>array_map(static fn(Node\Param $p):array=>['name'=>is_string($p->var->name)?'$'.$p->var->name:null,'span'=>Source::span($p),'byRef'=>$p->byRef,'variadic'=>$p->variadic],$scope->params)];}
}
